### ISSUE TITLE
Configuration file .toml is not correct

### ISSUE THREAD

**Issue by Timkokain** [teamfusion/rottencreatures#8]
The forge server prints out a message:
```txt
[main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file /data/config/rottencreatures-common.toml is not correct. Correcting
```
At the same time, he tries to re-create the mod's settings file. But it does it wrong.
I think the mod generates a settings file with custom representations of setting names instead of key names.
This is what it generates:
```toml
["Mob Spawns"]
	#determines how often will Burneds spawn
	"Burned Weight" = 20
	#determines how often will Frostbittens spawn
	"Frostbitten Weight" = 80
	#determines how often will Glacial Hunters spawn
	"Glacial Hunter Weight" = 20
	#determines how often will Swampies spawn
	"Swampy Weight" = 80
	#determines how often will Undead Miners spawn
	"Undead Miner Weight" = 20
	#determines how often will Mummies spawn
	"Mummy Weight" = 20
	#determines how often will Dead Beard spawn
	"Dead Beard Weight" = 1
	#determines the chance of spawning for Immortals
	"Immortal Chance" = 0.025
```
and this is how i try to fixed it:
```toml
[mobSpawns]
	#determines how often will Burneds spawn
	burned_weight = 20
	#determines how often will Frostbittens spawn
	frostbitten_weight = 80
	#determines how often will Glacial Hunters spawn
	glacial_hunter_weight = 20
	#determines how often will Swampies spawn
	swampy_weight = 80
	#determines how often will Undead Miners spawn
	undead_miner_weight = 20
	#determines how often will Mummies spawn
	mummy_weight = 20
	#determines how often will Dead Beard spawn
	dead_beard_weight = 1
	#determines the chance of spawning for Immortals
	immortal_chance = 0.025
```
But it did not help. When the server starts, it continues to produce backup copies of the settings.
